[package]
name = "parity-codec"
description = "Lightweight, efficient, binary serialization and deserialization codec"
version = "2.0.3"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"

[dependencies]
arrayvec = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = []

[workspace]
members = [
	"derive",
]
